# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admiral < Formula
  desc "Admiral CLI - Platform Orchestrator"
  homepage "https://admiral.io/"
  version "0.0.1"
  license "MPL-2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Darwin_x86_64.tar.gz"
      sha256 "58053af307c4e3866dcd35fe06bcaf040ed3bcb2b78a19286b804eac78c800a3"

      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Darwin_arm64.tar.gz"
      sha256 "9bfa706ea7bbcd8cd055ab154763eb6afaa1143e0442d9ae8d8b1bc327ee3016"

      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Linux_x86_64.tar.gz"
      sha256 "cd06817fe4db4ef44d1eb9ae78cc3186f2b2ca501818d82faa9706334f739433"
      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Linux_arm64.tar.gz"
      sha256 "69cae4c12a50940dcd2fce34abffc844aa05f3ff3c5587f0890ef3828cacd375"
      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  test do
    system "#{bin}/admiral --version"
  end
end
