# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Admiral < Formula
  desc "Admiral CLI - Platform Orchestrator"
  homepage "https://admiral.io/"
  version "0.0.1"
  license "MPL-2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Darwin_x86_64.tar.gz"
      sha256 "3bfa9bd830c72a82bcd3d2534bc76ebb73da580e3f57293fac9adc5790a0d2fc"

      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Darwin_arm64.tar.gz"
      sha256 "59bb85f4a8d84b1bb9b5fad0f76d25be8f12b7ba66612fbbda1752b9f1f5e8db"

      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Linux_x86_64.tar.gz"
      sha256 "7bf551546f86e6a122f14dea85d98c363c799804a5a6cd78241a1944243dd9e5"
      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/admiral-cli/releases/download/v0.0.1/admiral-0.0.1_Linux_arm64.tar.gz"
      sha256 "3ec09d9e6f90eeb10ec05df5c6e65e10cdbc9cd23de3de98f33bb42d033a9204"
      def install
        bin.install "admiral"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
      end
    end
  end

  test do
    system "#{bin}/admiral --version"
  end
end
