# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdmiralCli < Formula
  desc "Admiral CLI utility"
  homepage "https://admiral.io/"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/admiral/releases/download/v0.1.0/admiral-0.1.0_darwin_arm64.tar.gz"
      sha256 "338553661ef0e2558bddef5e95b54213b475217df0c41eace815b09c564ea164"

      def install
        bin.install "admiral"
        bin.install_symlink "admiral" => "adm"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
        man1.install "manpages/admiral.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/admiral/releases/download/v0.1.0/admiral-0.1.0_darwin_amd64.tar.gz"
      sha256 "2ee057ef5894a6b349e0dfd5d0fa69573209833688a59e69f18b71f393b159c5"

      def install
        bin.install "admiral"
        bin.install_symlink "admiral" => "adm"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
        man1.install "manpages/admiral.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/admiral/releases/download/v0.1.0/admiral-0.1.0_linux_arm64.tar.gz"
      sha256 "5dc672cba4ba86eef55206ffeffacf5a2f92939394d4e72c5e793b2b1ed03566"

      def install
        bin.install "admiral"
        bin.install_symlink "admiral" => "adm"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
        man1.install "manpages/admiral.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/admiral/releases/download/v0.1.0/admiral-0.1.0_linux_amd64.tar.gz"
      sha256 "cc22c0657e0dca468c3e93bdb08184b3f3661ec57cea465ca732033a13849da3"

      def install
        bin.install "admiral"
        bin.install_symlink "admiral" => "adm"
        bash_completion.install "completions/admiral.bash" => "admiral"
        zsh_completion.install "completions/admiral.zsh" => "_admiral"
        fish_completion.install "completions/admiral.fish"
        man1.install "manpages/admiral.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Admiral!
    EOS
  end

  test do
    system "#{bin}/admiral --version"
  end
end
