# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datalift < Formula
  desc "Datalift CLI utility"
  homepage "https://datalift.io/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_arm64.tar.gz"
      sha256 "b905970210f4eb3b4127227d877c1a85c4a008685b91a33b333eff6c46e80143"

      def install
        bin.install "datalift"
        bin.install_symlink "datalift" => "dl"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_amd64.tar.gz"
      sha256 "8537949e8d1effbdbc011eb57916bc036fb9aa4ab4cf781529658eac11224a19"

      def install
        bin.install "datalift"
        bin.install_symlink "datalift" => "dl"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_arm64.tar.gz"
      sha256 "bb3f7edd84a6278c6e8f11d74e5af42f771abd598a89d8c114e1cbef079842ef"

      def install
        bin.install "datalift"
        bin.install_symlink "datalift" => "dl"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_amd64.tar.gz"
      sha256 "a26d0cf807c6b44f26cb06bf58a00dddc8ce576bcd0b937a5eaf87ce74d752ef"

      def install
        bin.install "datalift"
        bin.install_symlink "datalift" => "dl"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Datalift!
    EOS
  end

  test do
    system "#{bin}/datalift --version"
  end
end
