# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datalift < Formula
  desc "Datalift CLI utility"
  homepage "https://datalift.io/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_arm64.tar.gz"
      sha256 "fc5842fb1f297b98dcd45f4b8003b1a3fd767abd780421966bb6bb1df03f190d"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_amd64.tar.gz"
      sha256 "7d2ab2c6e955894818bf89b9fbd988ae2e68e6daa4301cd739023090ca19bc23"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_amd64.tar.gz"
      sha256 "2c2a025b602eb713297e73c5fabdd47388d0449e2e2cbe705917ed400ef31a65"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_arm64.tar.gz"
      sha256 "2a93c7c9a060ca1204bc7a4dd4c9a02dde1f7c2d6095e9970abd7703daa80ffc"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Datalift!
    EOS
  end

  test do
    system "#{bin}/datalift --version"
  end
end
