# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datalift < Formula
  desc "Datalift CLI utility"
  homepage "https://datalift.io/"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_arm64.tar.gz"
      sha256 "e1bcbdc73e4ac52ae145fa22cb599761a940341d99faea6c34fdc2be7cb88881"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_darwin_amd64.tar.gz"
      sha256 "0dd79eaaee2444f96ad17693978ecab28f2235653265ef3405b7b1163dc9b871"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_arm64.tar.gz"
      sha256 "63985a2338b696866e9fb3e511e8627f84a7f1432702f100ca7e06e57b30f64c"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataliftHQ/datalift/releases/download/v1.0.0/datalift-1.0.0_linux_amd64.tar.gz"
      sha256 "16cd6a879c916a19466b3d639155939b94e1f5c2b5c3ef080228938cc4b53539"

      def install
        bin.install "datalift"
        bash_completion.install "completions/datalift.bash" => "datalift"
        zsh_completion.install "completions/datalift.zsh" => "_datalift"
        fish_completion.install "completions/datalift.fish"
        man1.install "manpages/datalift.1.gz"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Datalift!
    EOS
  end

  test do
    system "#{bin}/datalift --version"
  end
end
